const ORGANIC_ITEM_HEADER_BREADCRUMBS_ROOT_EL = 'div.q0vns div.CA5RN div.byrV5b cite.tjvcx.GvPZzd.cHaqb';
const ORGANIC_ITEM_ROOT_EL_STANDARD = 'div.MjjYud div.srKDX';
const ORGANIC_ITEM_ROOT_EL_EXTENDED = 'div.MjjYud div.BYM4Nd';
const ORGANIC_ITEM_ROOT_EL_COMMERCIAL = 'div.MjjYud div.N54PNb.BToiNc.cvP2Ce';
const ORGANIC_ITEM_ROOT_EL_YOUTUBE = 'div.MjjYud div.g.PmEWq';

export const CONSTS_DOM_ORGANIC_ITEM_ROOT_EL = `
  ${ORGANIC_ITEM_ROOT_EL_STANDARD},
  ${ORGANIC_ITEM_ROOT_EL_EXTENDED},
  ${ORGANIC_ITEM_ROOT_EL_COMMERCIAL},
  ${ORGANIC_ITEM_ROOT_EL_YOUTUBE}`.trim();

export const CONSTS_DOM_ORGANIC_ITEM_HEADER_ROOT_EL = 'div.kb0PBd.cvP2Ce.jGGQ5e, div.xe8e1b div.nhaZ2c';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_BREADCRUMBS_ROOT_EL = ORGANIC_ITEM_HEADER_BREADCRUMBS_ROOT_EL;
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_DOMAIN_ROOT_EL = 'div.q0vns span.VuuXrf';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_ICON_ROOT_EL = '.eqA2re.Vwoesf img';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_LINK_ROOT_EL = 'div.yuRUbf a, a';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_TITLE_ROOT_EL = 'h3.LC20lb.MBeuO.DKV0Md';

export const CONSTS_DOM_ORGANIC_ITEM_BODY_ROOT_EL =
  'div.VwiC3b.yXK7lf.lVm3ye.r025kc.hJNv6b, div.fzUZNc div.ITZIwc, div.VwiC3b.yXK7lf.r025kc.hJNv6b.Hdw6tb';

export const CONSTS_DOM_ORGANIC_ITEM_FOOTER_ROOT_EL = 'div.kb0PBd.cvP2Ce';
export const CONSTS_DOM_ORGANIC_ITEM_FOOTER_PROS_CONS_ROOT_EL = 'div span.ADx4Yb';
export const CONSTS_DOM_ORGANIC_ITEM_FOOTER_SECONDARY_REF_ROOT_EL = 'div.HiHjCd a';
