export const CONSTS_DOM_IMAGE_PACK_ROOT_EL = 'div.ULSxyf';
export const CONSTS_DOM_IMAGE_PACK_HEADER_ROOT_EL = '.Lv2Cle .x7cRLb';
export const CONSTS_DOM_IMAGE_PACK_HEADER_LINK_ROOT_EL = 'a';
export const CONSTS_DOM_IMAGE_PACK_HEADER_TEXT_ROOT_EL = '.mgAbYb.OSrXXb.RES9jf.IFnjPb';
export const CONSTS_DOM_IMAGE_PACK_ITEM_ROOT_EL = '.w43QB.EXH1Ce';
export const CONSTS_DOM_IMAGE_PACK_ITEM_FOOTER_ROOT_EL = '.T3Fozb.s2pXAe.OdBhM.zUdppc.ZTblUe';
export const CONSTS_DOM_IMAGE_PACK_ITEM_FOOTER_DOMAIN_ROOT_EL = '.LbKnXb.YAG2qc.UYJxh';
export const CONSTS_DOM_IMAGE_PACK_ITEM_FOOTER_ICON_ROOT_EL = '.oRVWZ.GB3ilc.Vwoesf img';
export const CONSTS_DOM_IMAGE_PACK_ITEM_FOOTER_TEXT_ROOT_EL = '.Yt787';
export const CONSTS_DOM_IMAGE_PACK_ITEM_IMG_ROOT_EL = '.kwICDb.DfMusf.y9pG6d.aVUpl';
export const CONSTS_DOM_IMAGE_PACK_ITEM_IMG_SRC_ROOT_EL = 'img';
export const CONSTS_DOM_IMAGE_PACK_ITEM_IMG_TEXT_ROOT_EL = 'img';
export const CONSTS_DOM_IMAGE_PACK_ITEM_LINK_ROOT_EL = '.ddkIM.c30Ztd';

export const CONSTS_DOM_ORGANIC_ITEM_ROOT_EL = '.MjjYud .srKDX.cvP2Ce';
export const CONSTS_DOM_ORGANIC_ITEM_BODY_ROOT_EL = 'div.VwiC3b.yXK7lf.lVm3ye.r025kc.hJNv6b span';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_ROOT_EL = 'div.kb0PBd.cvP2Ce.ieodic.jGGQ5e';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_BREADCRUMBS_ROOT_EL =
  'div.q0vns div.CA5RN div.byrV5b cite.qLRx3b.tjvcx.GvPZzd.cHaqb';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_DOMAIN_ROOT_EL = 'div.q0vns span.VuuXrf';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_ICON_ROOT_EL = '.eqA2re.UnOTSe.Vwoesf img';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_LINK_ROOT_EL = '.yuRUbf a';
export const CONSTS_DOM_ORGANIC_ITEM_HEADER_TITLE_ROOT_EL = 'h3.LC20lb.MBeuO.DKV0Md';
